arb-dir: l10n
template-arb-file: intl_en.arb
output-localization-file: naples_localizations.dart
output-class: NaplesLocalizations
#These properties are not working, but invoking gen_l10n works:
#flutter gen-l10n --arb-dir=l10n --template-arb-file=intl_en.arb --output-localization-file=naples_localizations.dart --output-class=NaplesLocalizations --no-synthetic-package --output-dir=lib/src/generated/l10n
synthetic-package: false
output-dir: lib/src/generated/l10n