name: naples
description: A View-Model framework from The Yellow Factory.
version: 0.0.1
author: null
homepage: null
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Internationalization support.
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2
  #end Internationalization support.
  provider: 5.0.0-nullsafety.3 
  list_ext: ^1.0.1-nullsafety.0
  flutter_markdown: ^0.5.2
  mustache_template: ^1.0.0+1
  markdown: ^3.0.0 #^4.0.0-nullsafety.0 --> Conflicts with flutter_markdown
  flutter_linkify: ^4.0.2
  url_launcher: ^6.0.0-nullsafety.4 
  #file_picker: ^2.1.0
  file_picker_cross: ^4.2.7
  path: ^1.8.0-nullsafety.3
  crimson:
    git: https://github.com/yellow-factory/crimson.git
  navy:   
    git: https://github.com/yellow-factory/navy.git

dependency_overrides:
  crimson:
    path: ../crimson
  navy:
    path: ../navy

dev_dependencies:
  flutter_test:
    sdk: flutter
  #intl_translation: ^0.17.10+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: 
  # Adds code generation (synthetic package) support 
  generate: false

#flutter_intl:
#  enabled: true

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
